Traceback (most recent call last):
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/snakemake/io.py", line 1707, in _load_configfile
    return yte.process_yaml(f, require_use_yte=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/yte/__init__.py", line 36, in process_yaml
    yaml_doc = yaml.load(file_or_str, Loader=yaml.FullLoader)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found ','
  in "/hpc/projects/data.science/yangjoon.kim/zebrahub_multiome/data/processed_data/TDR118_cicero_output/01_TDR118_CRG_arc_peaks.csv", line 1, column 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/bin/snakemake", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/snakemake/__init__.py", line 3141, in main
    success = snakemake(
              ^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/snakemake/__init__.py", line 570, in snakemake
    update_config(overwrite_config, load_configfile(f))
                                    ^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/snakemake/io.py", line 1720, in load_configfile
    config = _load_configfile(configpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mydata/yang-joon.kim/anaconda/23.1.0-3/x86_64/envs/snakemake/lib/python3.11/site-packages/snakemake/io.py", line 1709, in _load_configfile
    raise WorkflowError(
snakemake.exceptions.WorkflowError: Config file is not valid JSON or YAML. In case of YAML, make sure to not mix whitespace and tab indentation.
